### ISSUE TITLE
[Visualizador] Problema con nombre de entidad mostrado

### ISSUE THREAD

**Issue by mar-esther23** [cnb-angelus/AngelusIssues#112]
**Describe el problema**
No se muestra nombre más actual aun cuando agregas propiedad tiene nombre nueva

**Cómo reproducir**

**Comportamiento esperado**
Puede ser mostrar nombre nuevo o uno por default, depende del caso
Mejorar criterio de seleccionar nombre
Tal vez seleccionar nombre por default

**Capturas de pantalla**

**Escritorio (complete la siguiente información):**

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by syats** [comment]
En el visualizador se puede escoger cual mostrar.
En el anotador y en el visualizdor, todas las búsquedas son por texto, así que encontrarán la entidad sin importar el nombre que pongan en la cajita de búsqueda.

**Comment by syats** [comment]
Relacionado con #152  en que se agregó por error un nombre, y ahora se ve este con el visualizador

**Comment by syats** [comment]
Tiene que ser consistentemente el último `tieneNombre` agregado (platicado con Esther y Donají 20220718)
