### ISSUE TITLE
[Anotacion] Manual

### ISSUE THREAD

**Issue by mar-esther23** [cnb-angelus/AngelusIssues#114]
**Documento**
Manual de captura

**Describe el problema**
Como ir al documento desde una entidad
Cómo seleccionar el documento?
Como ver doc que sustenta propiedades como tieneNombre

**Describe la solución que te gustaría**
Una descripción clara y concisa de lo que quieres que suceda.

**Describe las alternativas que has considerado**
Una descripción clara y concisa de cualquier solución o característica alternativa que haya considerado.

**Contexto adicional**
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí.

**Comment by syats** [comment]
Hay que actualizarlo cuando quede lista la siguiente versión del anotador.
