### ISSUE TITLE
[Anotador] Problema con agregar propiedad "género" a una entidad nueva o existente

### ISSUE THREAD

**Issue by donajivalencia** [cnb-angelus/AngelusIssues#117]
**Describe el problema**
Cada que intento agregar la propiedad "género" a una entidad, ya sea nueva o existente, el anotador no reacciona. 

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a cualquier documento del anotador que mencione una entidad persona y seleccione la entidad existente de la misma.
2. Haga clic en ' E ' para editar propiedades, intente agregar la propiedad género
3. Ver error

**Comportamiento esperado**
Debería guardar la propiedad

**Capturas de pantal
![Captura de Pantalla 2021-12-08 a la(s) 11 08 16](https://user-images.githubusercontent.com/77068058/145252851-ffa1a7f1-5026-4eb5-ad10-edf51c22ac38.png)
la**

**Escritorio (complete la siguiente información):**
 - SO: [MacOS Monterrey]
 - Navegador [p. Ej. chrome]
 - Versión del Navegador [p. Ej. 96]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by donajivalencia** [comment]
En general hay problemas con la propiedad "género", véase lo desplegado en la lista de entidades para establecer una relación.
![Captura de Pantalla 2021-12-08 a la(s) 12 15 38](https://user-images.githubusercontent.com/77068058/145261907-47e3844e-3960-4ebb-8488-2285cbc44685.png)

**Comment by FerchoCAlmanza** [comment]
Hoy aprox. a las 3 pm. empecé a tener el mismo problema para agregar la propiedad ''género'' a una entidad nueva, pues también está siendo desplegada como relación 
![image](https://user-images.githubusercontent.com/93741402/147023347-d2087d30-26cb-43c3-bd18-0accce040e89.png)

**Comment by FerchoCAlmanza** [comment]
En la siguiente foja surge la misma falla y además aparecen duplicadas un par de relaciones 
![image](https://user-images.githubusercontent.com/93741402/147032132-4712e490-85f0-4f23-a273-9aafa12c017d.png)
