### ISSUE TITLE
[Anotador] Mejora: No se respeta el orden de las páginas al ver un documento multipágina

### ISSUE THREAD

**Issue by Gabycruz2021** [cnb-angelus/AngelusIssues#118]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.**
Cuando busco un documento multipágina en el visualizador, no aparecen en el orden las páginas, ejemplo: Aparece la página 1-4 y después 11-15 y luego la 5, etc 

**Describe la solución que te gustaría**
Que aparezcan las páginas del documento numeradas

**Describe las alternativas que has considerado**
Escribir las páginas con formato de tres siglas ejemplo "001, 002"

**Contexto adicional**
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función:

<img width="326" alt="Captura de Pantalla 2021-12-09 a la(s) 11 13 30 a m" src="https://user-images.githubusercontent.com/78180774/145443785-0cbcddc6-189b-44d5-a57b-665d4b6ca8e5.png">

**Comment by syats** [comment]
En APIDocumentos, ponerle padding al número de página

**Comment by eduherrer8** [comment]
Ya quedó mezclado en el PR https://github.com/cnb-angelus/api_documentos/pull/24
