### ISSUE TITLE
[Anotador] Problema con modificación de entidad

### ISSUE THREAD

**Issue by gersanat** [cnb-angelus/AngelusIssues#12]
**Describe el problema**
No se pueden modificar una entidad

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Cuando se intenta modificar la entidad Miguel Valerio para añadir ocupación estudiante, el anotador no responde. 
2. Ver error

**Añadir ocupación a la etidad Miguel Valerio**

Por alguna razón no puedo añadir la categoría estudiante a Miguel Valerio, y se queda así (creo que está trabado):

**Capturas de pantalla**

![imagen](https://user-images.githubusercontent.com/77067879/103795453-9afbfd00-500b-11eb-8b7f-a3b5c75b3c3e.png)

**Escritorio (complete la siguiente información):**
 - SO: Windows
 - Navegador Firefox
 - Versión del Navegador [84.0.1]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by donajivalencia** [comment]
Sugerencia: En algunas ocasiones, no se despliegan las entidades ya creadas en otros documentos, por ejemplo DFS. Se sugiere poder “jalar” las entidades de cada expediente (y no cada foja) para limitar el número total de entidades que muestra el menú.

**Comment by mar-esther23** [comment]
> ejemplo

No me queda claro si este es otro issue o una sugerencia de solución al problema original

**Comment by gersanat** [comment]
Donají, me parece que esa es una sugerencia aparte. Podrías borrar este comentario y yo lo subo como sugerencia aparte

**Comment by syats** [comment]
Si esto vuelve a pasar, podrían, cuando está congelada la página, abir en otro tab el visualizador y apuntar aquí si se les vuelve a pedir credenciales (usuario / contraseña) o no.  Gracias!
