### ISSUE TITLE
[Anotador] Problema con abrir documentos de la lista

### ISSUE THREAD

**Issue by Gabycruz2021** [cnb-angelus/AngelusIssues#120]
**Describe el problema**
No puedo abrir los documentos de la lista del anotador 

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a https://dev-anotador.pruebascnb.org/#/
2. Haga clic en el lapiz del lado de recho 
3. Ver error por que no despliega el documento

**Comportamiento esperado**
Eesperaría que se abriera un documento

**Capturas de pantalla**

<img width="1353" alt="Captura de Pantalla 2021-12-09 a la(s) 11 42 11 a m" src="https://user-images.githubusercontent.com/78180774/145448311-77af02e1-71e5-4d74-9765-10cf7c21fb69.png">

**Escritorio (complete la siguiente información):**
 - SO: [MacOS]
 - Navegador [Chrome]
 - Versión del Navegador [9]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by normatrinidad** [comment]
Este comportamiento no ocurre actualmente en la versión que está en https://dev-anotador.pruebascnb.org/
