### ISSUE TITLE
[DEV] Problema con visualizar botones de entidad en pantalla de 885 x 1704

### ISSUE THREAD

**Issue by Gabycruz2021** [cnb-angelus/AngelusIssues#122]
**Describe el problema**
en la pantalla del anotador al visualizar un documento y querer agregar propiedades no puedo visualizar los botones de la derecha a menos de que haga mi pantalla del navegador larga, ni siquiera utilizando el zoom

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a https://dev-anotador.pruebascnb.org/#/anotador/XBDDK2%2FMU3I3Q
2. Haga clic en Entidades, agregar entidad nueva o existente
3. Ver error

**Comportamiento esperado**
Esperaría que no deba de hacer grande mi pantalla para visualizar los botones para agregar entidades 

**Capturas de pantalla**
<img width="1440" alt="Captura de Pantalla 2021-12-22 a la(s) 10 25 10 a m" src="https://user-images.githubusercontent.com/78180774/147123965-ecbc6d1b-d925-4310-bbd7-a848ed94748a.png">

 - SO: [Mac]
 - Navegador [Chrome]
 - Versión del Navegador [p. Ej. 22]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by normatrinidad** [comment]
<img width="814" alt="Captura de Pantalla 2022-01-17 a la(s) 3 02 31" src="https://user-images.githubusercontent.com/6715074/149739567-07ef8db3-f981-440f-b823-d03a367dff4a.png">
<img width="813" alt="Captura de Pantalla 2022-01-17 a la(s) 3 02 46" src="https://user-images.githubusercontent.com/6715074/149739576-363123be-b382-4dfd-b5f1-d8dfc4516cf6.png">
