### ISSUE TITLE
[Dev] Problema con agregar anotaciones sobre entidades nuevas 

### ISSUE THREAD

**Issue by Gabycruz2021** [cnb-angelus/AngelusIssues#123]
**Describe el problema**
Una descripción clara y concisa del problema

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a '...'
2. Haga clic en '....'
3. Desplácese hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Una descripción clara y concisa de lo que esperaba que sucediera.

**Capturas de pantalla**
<img width="1378" alt="Captura de Pantalla 2021-12-22 a la(s) 10 34 50 a m" src="https://user-images.githubusercontent.com/78180774/147125578-01f67d21-656a-4176-9532-034f131c2ce8.png">

**Escritorio (complete la siguiente información):**
 - SO: [p. Ej. Windows, Mac]
 - Navegador [p. Ej. cromo, safari]
 - Versión del Navegador [p. Ej. 22]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by syats** [comment]
![Uploading mencion_nueva_entidad.png…]()

**Comment by syats** [comment]
Creo que ya quedó. Verificar porfavor.

**Comment by syats** [comment]
Listo :)
