### ISSUE TITLE
[DEV] Problema con invalidar propiedades

### ISSUE THREAD

**Issue by Gabycruz2021** [cnb-angelus/AngelusIssues#124]
**Describe el problema**
El botón para invalidar propiedades no funciona

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a (https://dev-anotador.pruebascnb.org/#/anotador/QW1DJJ%2F5P8AU4)
2. Haga clic en cualquier propiedad
3. Trata de invalidar la propiedad
4. Ver error

**Comportamiento esperado**
Que el botón de invalidar invalidara la propiedad

**Capturas de pantalla**
<img width="1552" alt="Captura de Pantalla 2021-12-22 a la(s) 10 54 19 a m" src="https://user-images.githubusercontent.com/78180774/147127946-58514c87-862a-4aef-92d4-010475e0ccd0.png">

**Escritorio (complete la siguiente información):**
 - SO: [Mac]
 - Navegador [Chrome]
 - Versión del Navegador [p. Ej. 22]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by syats** [comment]
![invalidar](https://user-images.githubusercontent.com/16990107/147128248-4b6ea0c6-19a1-4ce4-8a7e-16b985c6feaa.png)

**Comment by eduherrer8** [comment]
Se arregla en https://github.com/cnb-angelus/api_ontologia/pull/28
