### ISSUE TITLE
[Anotador, Pruebas] Problema para agregar propiedades adicionales

### ISSUE THREAD

**Issue by FatimaGranillo** [cnb-angelus/AngelusIssues#129]
**Describe el problema**
La página crashea cuando se intentan agregar propiedades adicionales (género y ocupación) a entidades existentes.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a Anotador-Angelus Pruebas y abra un documento de la lista.
2. Haga clic en "Clases a elegir" de la barra entidades.
3. Seleccione "Víctima directa".
4. Seleccione una entidad existente de la lista.
5. Oprima el botón E para añadir propiedades adicionales.
6. Llenar las propiedades Género y/o Ocupación.
7. Ver error al oprimir "Aceptar Propiedad" en caso de la propiedad adicional Ocupación.
8. Ver error al oprimir "Propiedades Adicionales Listas" en caso de la propiedad adicional Género.

**Comportamiento esperado**
Las propiedades entran al presionar Aceptar Propiedad, se puede proceder a oprimir Propiedades Adicionales Listas y en seguida a Agregar Anotaciones.

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/91276268/149801623-b2f41b97-f03f-4826-9070-f0c440aad8b7.png).

**Escritorio (complete la siguiente información):**
 - SO: [Windows]
 - Navegador [chrome]
 - Versión del Navegador [Versión 97.0.4692.71]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by mar-esther23** [comment]
Resuelto en AnotadorV2
