### ISSUE TITLE
[Anotador] Mejora: modificar nombre de entidades

### ISSUE THREAD

**Issue by donajivalencia** [cnb-angelus/AngelusIssues#13]
**¿Su solicitud de función está relacionada con un problema?**
 No se puede modificar el nombre de una entidad que tiene errores de ortografía.

**Describe la solución que te gustaría**
Poder hacer modificaciones del nombre de la entidad aun cuando ya se haya registrado. O que se pueda reconocer en el caso de que alguien quiera registrar la misma entidad escrita correctamente.

**Describe las alternativas que has considerado**
Añadir un comentario en observaciones.

**Contexto adicional**
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí.

**Comment by mar-esther23** [comment]
![index](https://user-images.githubusercontent.com/3729522/103838224-20a29b80-5052-11eb-8d78-febbbb7c8bc1.jpeg)

**Comment by donajivalencia** [comment]
“Detención” y “Captura” están generando ambigüedad, porque la palabra “detención” también denota el momento en que se priva de la libertad. Sugiero cambiarla por “cautiverio”, que desambigua completamente.

**Comment by mar-esther23** [comment]
> “Detención” y “Captura” están generando ambigüedad, porque la palabra “detención” también denota el momento en que se priva de la libertad. Sugiero cambiarla por “cautiverio”, que desambigua completamente.

Este es un asunto no relacionado con este issue, se a generado un issue al respecto.

**Comment by mar-esther23** [comment]
No se arreglara esta situación en esta versión del anotador.

Como solución temporal se sugiere:
* Opción 1: agregar al atributo Nombre con errores la observación: "[DELETE]" y crear un atributo Nombre nuevo con los datos correctos
* Opción 1: agregar al atributo Nombre con errores la observación: "[CORRECT]: nombre correcto" y poner el nombre correcto dentro de la observación
* 

 agregar una observación que diga:
[]
