### ISSUE TITLE
[Visualizador] Mejora: Ampliación de pantalla

### ISSUE THREAD

**Issue by donajivalencia** [cnb-angelus/AngelusIssues#130]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.**
Cuando hay muchas entidades y eventos relacionados entre sí, es complicado visualizarlo con claridad

**Describe la solución que te gustaría**
Que la pantalla blanca pudiera ampliarse para hacer grafos más grandes, con más relaciones.

**Contexto adicional**
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí.
![Captura de Pantalla 2022-01-21 a la(s) 12 16 54](https://user-images.githubusercontent.com/77068058/150579647-8a4e6681-1739-47ce-bcb4-f2c5b5f1eca2.png)

**Comment by Bastian-Kass** [comment]
Este problema se resuelve con la funcionalidad de "Tamano de lienzo"?

![image](https://user-images.githubusercontent.com/6613145/178731197-3a3a2593-e26a-4bd8-8dff-e610e1a7e507.png)
