### ISSUE TITLE
[Anotador] Problema con agregar propiedades a una nueva entidad

### ISSUE THREAD

**Issue by Gabycruz2021** [cnb-angelus/AngelusIssues#133]
**Describe el problema**
Al entrar al visualizador con credenciales de invalidador no se puede agregar propiedades nuevas a una entidad 

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'Visualizador y entre con datos de invalidador
2. Haga clic en cualquier documento
3. Desplácese hacia abajo hasta agregar una propiedad a una entidad
4. Ver error

**Comportamiento esperado**
Uno espera que al guardar cambios se puedan ver en el visualizador las propiedades nuevas de la entidad pero eso no sucede.

**Capturas de pantalla**
Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.
Opriman F12, debe aparecer una barra abajo, revisen estar en el tab de Console y capturen la pantalla con ImpPt.

**Escritorio (complete la siguiente información):**
 - SO: [Mac]
 - Navegador [Chrome]
 - Versión del Navegador [p. Ej. 22]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by mar-esther23** [comment]
Es necesario dar refresh para ver los cambios, hacer notar esto a los usuarios
