### ISSUE TITLE
[Productivo] Problema con Anotador 

### ISSUE THREAD

**Issue by Carloscalavera603** [cnb-angelus/AngelusIssues#137]
**Describe el problema**
Al abrir el Anotador, este no carga los documentos.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'Sistema productivo del Anotador'
4. Ver error

**Comportamiento esperado**
Al abrir el Anotador espero poder ver los documentos cargados. 
![Captura de pantalla (2)](https://user-images.githubusercontent.com/93740967/152616657-c14c5f1b-443d-4d03-a16c-65f788540799.png)

**Capturas de pantalla**

**Escritorio (complete la siguiente información):**
 - SO: [Windows]
 - Navegador [cromo]
 - Versión del Navegador [96.0.4664.110]

**Contexto adicional**

**Comment by FatimaGranillo** [comment]
> **Describe el problema** No termina de cargar el  Anotador Pruebas.
> 
> **Cómo reproducir** Pasos para reproducir el comportamiento:
> 
> 1. Ingrese al 'Sistema productivo del Anotador'
> 2. Ver error
> 
> **Comportamiento esperado** Que cargue la lista de documentos del Anotador y se pueda dar click en alguno.
> 
> **Capturas de pantalla** ![image](https://user-images.githubusercontent.com/91276268/152617809-1043356a-65b4-47d3-81a3-f884c2d4470a.png)
> 
> **Escritorio (complete la siguiente información):**
> 
> * SO: [Windows]
> * Navegador [Google Chrome]
> * Versión del Navegador [97.0.4692.99]
> 
> **Contexto adicional** La lista de documentos tampoco termina de cargar en navegadores Edge y Firefox

**Comment by ElizabethNava** [comment]
[Productivo] Problema con Anotador 
Describe el problema
El Anotador no carga los documentos.

Cómo reproducir
1.-Vaya a 'Sistema productivo del Anotador'
2.-Ver error

Comportamiento esperado
Al abrir el Anotador poder ver los documentos cargados.

Capturas de pantalla 
![image](https://user-images.githubusercontent.com/87724450/152842435-c4e211c6-d2b5-4a1b-8dac-e8b815a0a0b4.png)

Escritorio (complete la siguiente información):

SO: [Windows]
Navegador [Google Chrome]
Versión del Navegador [97.0.4692.99]

Contexto adicional: La lista de documentos tampoco es visible en navegador Brave.

**Comment by syats** [comment]
Solucionado
