### ISSUE TITLE
[Api Ontologia] Api no regresa propiedades invalidadas

### ISSUE THREAD

**Issue by Bastian-Kass** [cnb-angelus/AngelusIssues#155]
**Describe el problema**

Usuario con permisos de invalidador
Url accessada: 'entities/by_ids_dictionary'

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Accessar al api como usuario **invalidador**
2. Hacer request de una o mas entidades: Ejemplo: 
     ['<https://entidades.pruebascnb.org/lugares/ColimaColima_82543b>', 
      '<https://entidades.pruebascnb.org/lugares/ComalaColima_7e94c7>',
      '<https://inegi.gob.mx/AGEEML/2021/06003>']

4. Consultar el subconjunto(objeto) llamado 'data_properties'
5. Las entidades mentionadas en el paso dos deberian de tener propiedades invalidadas

**Comportamiento esperado**
Si el usuario tiene permisos de invalidador, el API deberia regresar tambien las propiedades invalidadas dentro de cada una como:
'uri-de-la-propiedad'.provenance.is_valid: true/false

**Comment by syats** [comment]
Para empezar a debugear esto: @Bastian-Kass  podrías copiar acá el request que estás haciendo para invalidar las propiedades?

**Comment by syats** [comment]
@Bastian-Kass  same as #158  ?
