### ISSUE TITLE
[API Ontologia] Agregar una relacion a traves del anotador no regresa el uri de la anotacion

### ISSUE THREAD

**Issue by Bastian-Kass** [cnb-angelus/AngelusIssues#157]
**Describe el problema**
Al agregar una relacion por medio del endpoint (POST : /annotation/new_relation), el backend regresa el id de la relacion materializada, pero no regresa el uri de la anotacion; lo cual hace conflictivo el manejo de las relaciones ya que estos cambios no se ven en otras consultas hasta que pasan unos minutos.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Acceda a  (POST: /annotation/new_relation)
2. Los parametros por ejemplo pueden ser:

> {
    "location": {
        "soporte_documental": "<https://documentos.pruebascnb.org/ANGELUS/EOFGPH/CXSHVX>",
        "annotation_date": null,
        "is_valid": true
    },
    "specific_provenance": {
        "observaciones": "sdfsdf",
        "confianza": "<https://vocabularios.pruebascnb.org/v1.0/Confianza/Positiva>",
        "metodo_inferencia": null,
        "validity_period": {
            "start_date_lower_bound": null,
            "start_date_upper_bound": null,
            "end_date_lower_bound": null,
            "end_date_upper_bound": null
        }
    },
    "predicate": "<https://ontologias.pruebascnb.org/v1.0/estaEnLugar>",
    "subject": "<https://entidades.pruebascnb.org/lugares/ColimaColima_82543b>",
    "object": "<https://entidades.pruebascnb.org/lugares/ColimaColima_82543b>",
}

4. Llamar al endpoint
5. La respuesta se vera asi:

![image](https://user-images.githubusercontent.com/6613145/183382310-f942f63c-a316-41aa-b664-78c26ce65b32.png)

**Comportamiento esperado**
La respuesta, ademas de regresar el uri de la relacion recien creada, deberia de regresar el uri de la mencion que lo liga al documento;
La que se encuentra bajo el objeto location -> anotation cuando se hace una consulta cualquiera

**Contexto adicional**
annotation_date bajo location tambien deberia de ser llenado por el servidor automaticamente

**Comment by syats** [comment]
@Bastian-Kass  desplegué un feature en Test que cubre estos cambios. Podrías checar que sea suficiente y que no se rompa nada, porfa?
Los endpoints que ahora devuelven URI de la anotación son 

```
POST {{api_onto}}/annotation/new_entity
POST {{api_onto}}/annotation/existing_entity
POST {{api_onto}}/annotation/new_relation
```

**Comment by Bastian-Kass** [comment]
> @Bastian-Kass desplegué un feature en Test que cubre estos cambios. Podrías checar que sea suficiente y que no se rompa nada, porfa? Los endpoints que ahora devuelven URI de la anotación son
> 
> ```
> POST {{api_onto}}/annotation/new_entity
> POST {{api_onto}}/annotation/existing_entity
> POST {{api_onto}}/annotation/new_relation
> ```

para 'annotation/new_entity' responde correctamente con el id de la anotacion
![image](https://user-images.githubusercontent.com/6613145/183710148-9713fa1d-bb57-4fb8-a27a-6254b9d66bb1.png)

Pero como ese endpoint tambien admite propiedades, y en teoria muchas anotaciones (locations), seria posible responder con el estado actual de la entidad, y con todas las locaciones al mismo documento?

**Comment by syats** [comment]
@Bastian-Kass  ,
Según yo ya esta :) Puedes checar en el ambiente de test a ver si esta respuesta es la que esperas?
