### ISSUE TITLE
[API Ontologia]  Usuario invalidados no tiene accesso a las objectos invalidos (is_valid: false)

### ISSUE THREAD

**Issue by Bastian-Kass** [cnb-angelus/AngelusIssues#158]
**Describe el problema**
Todos los endpoints que consultan tanto menciones de entidades, relaciones o propiedades no estan regresando las mismas si estan marcadas como is_valid: false

En caso de ser un usuario con permisos de invalidador ->

> GET: entities/by_document?document_id=

mentioned_entities -> regresar las entidades mencionadas no validas
mentioned_relations -> regresar las relaciones no validas

> POST: entities/by_ids_dictionary

data_properties, object_properties, e inverse properties no validas

> GET: entities/by_id?entity_id=

data_properties, object_properties, e inverse properties no validas

> PATCH: entities/by_id

data_properties, object_properties, e inverse properties no validas

> GET: entities/by_class_with_labels?class_id=

data_properties, object_properties, e inverse properties no validas

> POST: annotation/existing_entity

data_properties, object_properties, e inverse properties no validas

**Comment by syats** [comment]
@Bastian-Kass  puedes checar en el servidor de Test a ver si ya está bien?
Como ejemplo yo veo que en 
`{{api_onto}}/entities/by_document?document_id=<https://documentos.pruebascnb.org/ANGELUS/EOFGPH/CXSHVX> ` hay una anotación de entidad inválida. 
Y si luego quiero ver los detalles de una entidad con:
`{{api_onto}}/entities/by_id?entity_id=<https://entidades.pruebascnb.org/lugares/LugarParaInvalidar2_0088d2>` veo también una propiedad inválida. 

¿Es este el comportamiento esperado?
