### ISSUE TITLE
[Anotador] Permite agregar más de una mención a la misma entidad.

### ISSUE THREAD

**Issue by Mitl-AR** [cnb-angelus/AngelusIssues#17]
**Describe el problema**
Existe la posibilidad de repetir más de una vez la misma entidad. 

**Comportamiento esperado**
Una notificación del sistema indicando que esa entidad ya se encuentra previamente mencionada. 

**Capturas de pantalla**
![imagen](https://user-images.githubusercontent.com/77067930/103818858-e70c6900-502e-11eb-86cc-6733d77c15b8.png)

**Comment by syats** [comment]
Esta funcionalidad es esperada, pues se prevee poder diferencias anotaciones (e.g. en distintos párrafos). No tiene sentido ahorita que no se puede anotar en qué lugar exacto está la entidad, pero tendrá sentido cuando eso se pueda hacer :)
