### ISSUE TITLE
[Visualizador] El buscador no encuentra nodos existentes. 

### ISSUE THREAD

**Issue by efrainnavarro** [cnb-angelus/AngelusIssues#20]
**Describe el problema**
El buscador del visualizador no encuentra nodos existentes.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'Visualizador'
2. Haga clic en 'campo de búsqueda'
3. Teclee búsqueda de nombre completo de cualquier nodo existente.
4. Ver error

**Comportamiento esperado**
Que el buscador encontrara el nodo existente.

**Capturas de pantalla**
Búsqueda de Omar:

![1](https://user-images.githubusercontent.com/77067954/103830448-c947ff80-5040-11eb-8cee-92cd14e7eaba.png)
![2](https://user-images.githubusercontent.com/77067954/103830460-c9e09600-5040-11eb-925f-1ec67b7d29f9.png)

**Escritorio (complete la siguiente información):**
 - SO: Windows
 - Navegador [Chrome]
 - Versión del Navegador [Versión 87.0.4280.88]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by syats** [comment]
Al parecer es sensible a mayusculas/minusculas y diacríticos.
Hay otro campo en las respuestas del API que se pueden usar para busqueda. 
@syats  tiene que modificar esto para que sea solo minusculas e insensible a acentos. Después @Bastian-Kass  tendrá que modificar el front para usar este campo y para pasar a lowercase lo que esté venga de los cuadritos de búsqueda
