### ISSUE TITLE
[Visualizador] Problema con área de texto de tarjetas

### ISSUE THREAD

**Issue by efrainnavarro** [cnb-angelus/AngelusIssues#26]
**Describe el problema**
El visualizador no reconoce el final del área de escritura.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'Visualizador'
2. Agregar una tarjeta con nombre largo.
4. Ver error

**Comportamiento esperado**
Que el nombre de la tarjeta aparezca solamente en el área de la misma.

**Capturas de pantalla**

![3](https://user-images.githubusercontent.com/77067954/103834503-31024880-5049-11eb-9a0b-1956ce12bcf2.png)

**Escritorio (complete la siguiente información):**
 - SO: [Windows]
 - Navegador [Chrome]
 - Versión del Navegador [Versión 87.0.4280.88]

**Contexto adicional**

**Comment by donajivalencia** [comment]
En los comentarios de las minutas también se sugiere que cada ficha del visualizador tenga un color específico para cada tipo persona, organización, etc. Creo que esa mejora y esta sugerencia harían mucho más dinámico el grafo.

**Comment by syats** [comment]
parece que está bien en esta versión
