### ISSUE TITLE
[Visualizador] Duplicación de tarjetas y perdida de relaciones

### ISSUE THREAD

**Issue by efrainnavarro** [cnb-angelus/AngelusIssues#27]
**Describe el problema**
Al agregar  tarjetas se duplican y al eliminar las extras se borran ambas.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
Saqué la tarjeta DFS del tarjetero, y la misma la saqué desde la tarjeta con la que está relacionada (Esteban Guzmán): el visualizador duplicó la ficha (una relacionada con Esteban, otra aislada). Borré la que estaba aislada, borró ambas. Volví a sacar del tarjetero la de DFS, quedó aislada, y la relación volando. 

**Comportamiento esperado**
Que no se duplicaran las tarjetas.

**Capturas de pantalla**
![4](https://user-images.githubusercontent.com/77067954/103835112-f699ab00-504a-11eb-8db2-a58a00f094aa.png)

**Escritorio (complete la siguiente información):**
 - SO: [p. Ej. Windows, Mac]
 - Navegador [p. Ej. cromo, safari]
 - Versión del Navegador [p. Ej. 22]

**Contexto adicional**
Problema originalmente reportado por Javier Yankelevich. No cuento con las características de su SO y navegador. No pude replicarlo.

**Comment by donajivalencia** [comment]
Además de eso, ¿hay forma de vincular, automáticamente dos entidades idénticas sin que se repitan? Ver imagen de ejemplo. “Investigación penal de la desaparición forzada de Miguel Ángel Hernández Valerio.
![image](https://user-images.githubusercontent.com/77068058/103838672-4ed4ab00-5053-11eb-9bfd-206a875b67bf.png)

**Comment by donajivalencia** [comment]
También se menciona el problema de que en el documento **+ Documento Titulo: FEMOSP caso radilla Tomo 1 - Segundo Archivo - TomoI_4-6 - Página 2 ID: SVMIYH/YZSQG0**, algunas veces aparece dos veces Miguel Ángel Hernández Valerio.
![image](https://user-images.githubusercontent.com/77068058/103840574-73cb1d00-5057-11eb-9e1a-ccd6336dc49a.png)

**Comment by donajivalencia** [comment]
No encuentro una duplicación de relaciones en el anotador y al momento de poner "Brigada Blanca" en el visualizador, duplica la relación con la DFS
![image](https://user-images.githubusercontent.com/77068058/104081294-4b782580-51f3-11eb-88c0-a5cef525a92c.png)

SO:Windows
Chrome, versión 87

**Comment by syats** [comment]
Puede que ya esté arreglado en la última versión?  @Bastian-Kass asignamelo si crees que un redeploy lo solucione.

**Comment by Bastian-Kass** [comment]
Las tarjetas ya no se duplican, ahora se hace una relación con la tarjeta ya existente.

**Comment by Bastian-Kass** [comment]
Cuidado al checar que hay dos tarjetas llamadas "Direccion Federal de Seguridad"; una con el uri:

<https://entidades.pruebascnb.org/orggubernamentales/DireccinFederaldeSeguridad_b1e3e0>
<https://entidades.pruebascnb.org/orgperpetradoras/DireccinFederaldeSeguridad_dc079b>

**Comment by syats** [comment]
El error parece estar corregido
