### ISSUE TITLE
[Anotador] El anotador no permite establecer relaciones entre personas y algunos eventos

### ISSUE THREAD

**Issue by aaron271** [cnb-angelus/AngelusIssues#29]
**Describe el problema**
Una descripción clara y concisa del problema
El anotador permite relacionar personas con eventos del tipo “tortura”, pero no del tipo “detención” ni del tipo “captura”. 

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'relaciones'
2. Haga clic en 'Sujeto para seleccionar un evento; luego en Objeto, para seleccionar una persona'
3. Intente agregar un predicado para establecer una relación
4. Ver error

**Comportamiento esperado**
Que se puedan establecer relaciones entre personas y eventos, como "detención" y "captura"

**Capturas de pantalla**

![Captura 1](https://user-images.githubusercontent.com/77068624/103838490-ceae4580-5052-11eb-9756-37b9fd316eca.JPG)

![Captura](https://user-images.githubusercontent.com/77068624/103838541-f1405e80-5052-11eb-99c4-4c2925cf07db.JPG)

**Escritorio (complete la siguiente información):**
 - SO: Windows
 - Navegador: Firefox
 - Versión del Navegador

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by donajivalencia** [comment]
En el documento "Ficha CNDH José Barrón" se menciona a la Policía Federal como involucrada en la detención de José Barrón. Agregué la entidad nueva de la policía federal pero cuando quiero agregar la relación con la detención, el anotador no arroja ningún predicado.
![image](https://user-images.githubusercontent.com/77068058/103963130-2665b300-511e-11eb-8152-ec978235ef28.png)

SO: Windows
Navegador: Chrome
Versión: 87

**Comment by donajivalencia** [comment]
Pasa lo mismo con el resto de las relaciones. Aunque, por cierto, no sé si es posible o existe como predicado para la relación que la 'Comisión Nacional de Derechos Humanos' expide el documento/ficha de 'Detención de José Barrón'? ¿O cómo puedo añadirle a 'Detención de José Barrón' que también hay una ficha expedida por la CNDH? Porque en las observaciones de la entidad de la detención sólo se menciona la ficha emitida por la Seguridad Pública de Jalisco.

**Comment by donajivalencia** [comment]
El problema persiste. En el documento "La Brigada Blanca" (página 2) añadí la entidad persona "Luis Echeverría Álvarez" y la entidad evento "Creación de la Brigada Blanca" y el anotador no reconoce ningún predicado para las relaciones.
SO: Windows
Navegador: Chrome
Versión: 87
![image](https://user-images.githubusercontent.com/77068058/104047301-0f1ed800-51a7-11eb-86aa-dc58fa2502c2.png)

**Comment by donajivalencia** [comment]
En el documento de la Brigada Blanca (ahora página 5) se repite el problema cuando trato de relacionar la entidad persona "Arturo Durazo" como perpetrador de la entidad evento "Caso Río Tula"; el anotador no reconoce relaciones. He notado que sucede constantemente con eventos. Por ejemplo, en el caso mencionado anteriormente, no me dejaba agregar una relación entre la entidad organización perpetradora "DFS" ni de la organización "SEDENA" con la entidad evento "Creación de la Brigada Blanca", pero sí me dejaba establecer relaciones entre organizaciones. Es decir, entre "SEDENA" o "DFS" y "Brigada Blanca". 
![image](https://user-images.githubusercontent.com/77068058/104049966-78084f00-51ab-11eb-9cc1-ff5090a41090.png)

**Comment by gersanat** [comment]
Estoy en encontrando el mismo problema. No se puede añadir la relación Policía Judicial de Sinaloa "desapareció" a Miguel Ángel Hernández. Lo mismo sucede con la entidad 2 estudiantes desaparecidos junto con Miguel Ángel Hernández. 
![imagen](https://user-images.githubusercontent.com/77067879/104146188-76977c00-538f-11eb-8f36-f0966596dce7.png)

**Comment by donajivalencia** [comment]
El problema persiste en la relación entre organización y evento. No sobra señalar que en el campo del sujeto, el anotador no respeta el espacio designado para el texto. 
![image](https://user-images.githubusercontent.com/77068058/104769402-e1043f80-5734-11eb-8b67-2e22f7f64036.png)

SO:Windows
Navegador: Chrome
Verisón: 87

**Comment by donajivalencia** [comment]
El problema se repite en este documento cuando quiero colocar la relación de que el 48. Batallón de Infantería es perpetrador del Asesinato de Tolentino Barrera Muñoz
![image](https://user-images.githubusercontent.com/77068058/104832351-22404080-5856-11eb-9f82-646d1e624a24.png)

**Comment by syats** [comment]
Gracias por reportar. Creo que estoy ya está corregido. 
En todo caso, hay que mantener el mente que los eventos siempre son Objetos de relaciones, puede que eso haya sido una fuente de confusión.

@donajivalencia  @gersanat  @aaron271   podrían porfavor checar que está funcionando como en la imágen?

![Screenshot_2021-02-07_20-51-50](https://user-images.githubusercontent.com/16990107/107157812-8bfbc800-6986-11eb-9b66-22699208241d.png)


Gracias!

**Comment by syats** [comment]
Por ahorita, hay que mantener en mente el órden de las relaciones. 
Por ejemplo     esOrdenoEvento   va de persona (sujeto)   a  evento (objeto).  
Si lo pones al revez, no funciona :(

Pero esto funcionará mejor en la siguiente versión, cuando tengamos relaciones inversas también en la ontología.

**Comment by syats** [comment]
Lo cierro. Si sigue ocurriendo, re abran por favor.
