### ISSUE TITLE
Complementando información sobre un mismo evento

### ISSUE THREAD

**Issue by JavierYankelevich** [cnb-angelus/AngelusIssues#3]
En un primer momento sabíamos de un evento que X fue detenido en CDMX. Creamos un evento, lo nombramos, le pusimos fecha, creamos el lugar, lo relacionamos, relacionamos a X con el evento. Gracias a una segunda fuente, sabemos que junto con X fueron detenidos A, B y C, y en la misma secuencia resultaron ejecutados D, E y F. Además, sabemos gracias a la segunda fuente la colonia de la CDMX en que ocurrió la captura de X. 
Preguntas: 
1. ¿Qué hacemos con el nombre del evento, que era "captura de X"?, ¿le creamos un nombre alternativo para reflejar que fueron capturados otros también?, ¿creamos un nuevo evento? ¿hay forma de relacionar dos eventos de modo que uno "sea parte" de otro?
2. ¿Podemos tener un evento de "captura de X, A, B y C y de asesinato de D, E y F", o forzosamente necesitamos dos? (uno para "captura de X, A, B y C", otro para "asesinato de D, E y F"? si queremos uno sólo para mantener la unidad de acción... cómo lo subclasificamos? ¿o lo creamos como evento genérico, sin subclasificación?
3. Si es el mismo usuario anotador el que procesa ambos documentos, se acordará de que ya había un evento de captura de X. Pero si son dos distintos, ¿qué tan probable es que, al anotar el segundo documento, identifique el evento de captura de X a partir de nomenclatura?

Este caso se da al anotar la captura de Alicia de los Ríos a partir de la entrevista que dio a Proceso (número 2305, 3-ene-2021), y luego intentar complementarla al anotar a partir de la carta que su homónima hija dirigió a testigos el 5-ene-2021 (https://centroprodh.org.mx/?flowpaper-lite-plugin=get-pdf&pdf=https://centroprodh.org.mx/wp-content/uploads/2021/01/CartaAliciaDeLosRios.pdf).

**Comment by syats** [comment]
Esto sugiere que hay que renombrar los ejemplos automáticamente, al menos para buscarlos a la hora de ir anotando. Algo que se podría hacer, sería complementar los nombres de las busquedas con otras propiedades. Es lo que se está haciendo con Persona (por eso aparece AL: alias AP: apellido_paterno... etc.).  Podríamos hacer que saliera algo parecido. 
En ese caso, en tu ejemplo: 
1) Capturas el evento "Captura de Alicia de los Ríos Merino (madre)".

Más adelante, te das cuenta que hay otros capturados y ejecutados. Entonces:
2) Creas las entidades JHGG, AMM, LGC, E, P y ASR
3) Anotas mención del evento, al buscarlo en la cajita te sale: 
   "Captura de Alicia de los Rios (madre) V: Alicia de los Rios"
4) Creas las relaciones:
     "JHGG" fue víctima en "Captura de Alicia de los Rios (madre)" 
      ...  
     "E" fue víctima en "Captura de Alicia de los Rios (madre)" 
5) La próxima vez que alguien busque el evento le saldrá en la cajita :  "Captura de Alicia de los Rios (madre) V: Alicia de los Rios; V: JHGG; .....  V: E" 

Problema: no sabemos que E,Py ASR fueron asesinados en este evento. Creo que ya habíamos descartado el poner varias relaciones Persona->Evento. Podemos re-considerar esto?

**Comment by mar-esther23** [comment]
Veo dos formas de modelar esto. 

Una es tomar el evento original "Captura ARM" con subclase Captura, agregarle la subclase Asesinato, agregar una segunda propiedad Nombre "Captura de ARM y Asesinato de ..." y agregar las nuevas relaciones esVictimaDirectaDeEvento.

La otra opción es hacer un segundo evento "Asesinato de ..." y unirlo con la relación esEventoRelacionado, pero esta opción debilitaría el grafo.

@syats no me queda claro a que te refieres con "poner varias relaciones Persona->Evento". Según yo si es posible hacer esto.

**Comment by mar-esther23** [comment]
La solución a este problema es:
1) Se asigna una nueva subclase al Evento según corresponda
2) Y se le agrega un nuevo nombre que refleje ambas subclases

@efrainnavarro @gersanat por favor pueden incluir esto en los criterios? Ya que este pongan cerrar el Issue y/o avisenme.

**Comment by efrainnavarro** [comment]
@mar-esther23 En este momento no se puede asignar una nueva subclase a un evento existente, ni tampoco cambiar el nombre a una entidad existente ¿cierto?

**Comment by mar-esther23** [comment]
No, pero estamos trabajando en ello

**Comment by efrainnavarro** [comment]
Ok, ya quedó esto anotado como criterio.
