### ISSUE TITLE
[Visualizador] No está variando el nombre para relaciones de parentesco recíprocas

### ISSUE THREAD

**Issue by aaron271** [cnb-angelus/AngelusIssues#30]
**Describe el problema**
No está variando el nombre para relaciones de parentesco recíprocas. En este ejemplo madre e hija son homónimas perfectas (agregué el paréntesis para aclarar quién es cada una de ellas), y la relación que se trazó es AdlRM(hija) ESHIJADE adlRM(madre). El visualizador denota que las dos son hijas de la otra de forma recíproca. 

**Comportamiento esperado**
Que al establecer una relación de parentesco entre dos personas el sistema indique de forma automática esta relación de forma adecuada, en este caso que una persona es hija de otra, y esa otra a su vez es madre de la primera.

**Capturas de pantalla**
![Captura 3](https://user-images.githubusercontent.com/77068624/103839560-4e3d1400-5055-11eb-8e7c-93eeedd9a293.JPG)

![Captura 4](https://user-images.githubusercontent.com/77068624/103839570-54cb8b80-5055-11eb-861f-03a163962955.JPG)

**Escritorio (complete la siguiente información):**
 - SO: Windows
 - Navegador: Firefox

**Comment by aaron271** [comment]
No sé si en este caso se intentó establecer también la relación de parentesco: adlRM(madre) EsProgenitorDe AdlRM(hija), y si el hecho de establecer esta otra relación ayude al sistema.

**Comment by donajivalencia** [comment]
El anotador no está reconociendo las relaciones de jerarquía entre clases y subclases: no pone en “personas” lo que fue clasificado como “familiares”, “víctimas directas”, etc. Esto complica bastante.

**Comment by JavierYankelevich** [comment]
> 
> 
> No sé si en este caso se intentó establecer también la relación de parentesco: adlRM(madre) EsProgenitorDe AdlRM(hija), y si el hecho de establecer esta otra relación ayude al sistema.

¿El sistema reconoce que A eshija de B es lo mismo que B esprogenitde y acumula las menciones en un solo listado independientemente de la dirección que plasmó el capturismo, o las acumula por separado?

**Comment by mar-esther23** [comment]
Este es en el fondo un error de la ontología, tenemos que revisar cuidadosamente las relaciones para asegurarnos que esten definidas las reciprocas y a partir de eso actualizar el anotador.

**Comment by syats** [comment]
en realidad es un bug del visualizador, que no está mostrando las direcciones en las fichas.  
Creo que debe arreglarse con un redeploy.

**Comment by syats** [comment]
parece estar listo en esta nueva versión
