### ISSUE TITLE
[Anotador] Problema con duplicación de entidades

### ISSUE THREAD

**Issue by donajivalencia** [cnb-angelus/AngelusIssues#31]
**Describe el problema**
 En el documento + Documento Titulo: FEMOSP caso radilla Tomo 1 - Segundo Archivo - TomoI_4-6 - Página 2 ID: SVMIYH/YZSQG0, algunas veces aparece dos veces Miguel Ángel Hernández Valerio.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'entidades mostradas en este documento'
2. En 'Documento Titulo: FEMOSP caso radilla Tomo 1 - Segundo Archivo - TomoI_4-6 - Página 2 ID: SVMIYH/YZSQG0'
3. Ver error

**Comportamiento esperado**
Sólo debe aparecer una vez

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/77068058/103840886-0f5c8d80-5058-11eb-9c6b-97fb6364063c.png)

**Escritorio (complete la siguiente información):**
 - SO: [Windows]
 - Navegador [chrome]
 - Versión del Navegador [87]

**Contexto adicional**

**Comment by donajivalencia** [comment]
De las minutas, comparto un comentario similar de Javier:
 Al actualizar la página del anotador, me permitió agregar una segunda mención a exactamente la misma entidad. Tal vez debería aparecer un cartel de error del tipo “la entidad ya ha sido mencionada en este documento”. Al mismo tiempo, agregar una segunda mención a la misma entidad en el documento fue la única forma en la que pude agregar un atributo nuevo a una entidad ya creada (en este caso, el alias “Susana” a la entidad con nombre “Alicia de los Ríos Merino (madre)”. La posibilidad de editar lo que acabas de hacer no sólo permitiría subsanar errores de captura al mismo anotador, sino también complementar entradas conforme avanzas en la lectura.

**Comment by mar-esther23** [comment]
Duplicado de #17
