### ISSUE TITLE
[Visualizador] Si hay dos entidades que están relacionadas con una tercera, el visualizador agrega dos veces la misma tarjeta

### ISSUE THREAD

**Issue by aaron271** [cnb-angelus/AngelusIssues#32]
**Describe el problema**
Si hay dos entidades que están relacionadas con una tercera, el visualizador se hace bolas y agrega dos veces la misma tarjeta.  En este ejemplo lo hace con la entidad: “Secretaría de la Defensa Nacional”.

Nota: el ejemplo tiene un error de captura, pues si bien Alicia estuvo en ambos lugares, cada uno de esos lugares debería tener un evento asociado, y ese evento un lugar, y aquí yo asocié dos lugares al mismo evento de “detención”. 

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'Visualizador'
2. Introduzca dos entidades distintas
3. Introduzca una tercera entidad relacionada con las dos entidades previas
4. Ver error en la duplicación de la misma tarjeta, en lugar de que se establezca solamente la relación

**Comportamiento esperado**
Que en lugar de duplicar la misma tarjeta, sólo indique la relación de las primeras entidades con la tercera.

**Capturas de pantalla**
![Captura 5](https://user-images.githubusercontent.com/77068624/103845205-310e4280-5061-11eb-8178-669faf518cf4.JPG)

**Comment by mar-esther23** [comment]
Duplicado de #27
