### ISSUE TITLE
[Visualizador] Listado completo de fuentes en la visualización

### ISSUE THREAD

**Issue by JavierYankelevich** [cnb-angelus/AngelusIssues#37]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.
Si uno quiere saber "qué sabemos de X", va a la visualización tipo wiki. Si uno quiere saber "¿cuáles son todos los documentos que mencionan a X?", ¿cómo hace? Supongamos que se ha anotado en muchos documentos "mención a Campo Militar N1". ¿Cómo recupero todos esos documentos? 

En este momento, en ese tipo de visualización, hay opción para ir desde la relación al conjunto de fuentes que la documentan, pero no encuentro algo semejante para los atributos. ¿Estoy buscando mal?

![imagen](https://user-images.githubusercontent.com/77034019/103909117-eb856000-50c8-11eb-94ea-2753409d1437.png)

**Describe la solución que te gustaría**
Un listado de todos los documentos con menciones a esa entidad en la visualización tipo wiki de esa entidad. Ya en un mundo feliz, un botón que los compile en un único PDF, poniéndoles sus datos catalográficos, y los exporte. 

**Describe las alternativas que has considerado**

**Contexto adicional**
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí.

**Comment by syats** [comment]
Es decir, agregar fuentes también para Data Properties

**Comment by mar-esther23** [comment]
En la sección de Documento en lugar de No disponible debería de mostrar los uris

**Comment by mar-esther23** [comment]
Esta pregunta no es tanto del visualizador sino de la generación automática de expedientes. Hay que generar la función en el API y a partir de eso ver como generar los expedientes. Dado el nivel de protección de datos personales recomiendo mantener este proceso separado del visualizador.

**Comment by syats** [comment]
Será cubierto con el Issue:  https://github.com/cnb-angelus/Ontograph/issues/3
