### ISSUE TITLE
[Repositorio] No se suben los documentos formato PDF en el primer intento

### ISSUE THREAD

**Issue by aaron271** [cnb-angelus/AngelusIssues#40]
**Describe el problema**
Cuando intento subir un documento PDF al repositorio y doy clic en ´Save Dataset', la página se pone de color blanco y se pasma. En el segundo intento ya se sube el documento sin problemas.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'Repositorio, y Multipagina, y suba un documento PDF'
2. Haga clic en 'Save Dataset'
4. Ver error, cuando se pone la página en blanco

**Comportamiento esperado**
Que el documento PDF se suba al repositorio en el primer intento.

**Capturas de pantalla**
![Captura](https://user-images.githubusercontent.com/77068624/103942707-6dd84900-50f6-11eb-89fd-9ed9e61df3d5.JPG)

**Escritorio (complete la siguiente información):**
 - SO: Windows
 - Navegador Firefox 
 - Versión del Navegador 84.0.2

**Comment by donajivalencia** [comment]
Me pasó lo mismo. La página sólo se quedó en blanco y ahí se quedó. Tuve que darle refresh para que reaccionara pero se borró todo y tuve que ingresar todo de nuevo.
SO: Windows
Navegador: Chrome
Versión: 87

**Comment by syats** [comment]
@syats  revisar logs en dataverse para ver que está pasando.

**Comment by syats** [comment]
Sigue pasando esto?
