### ISSUE TITLE
[Anotador] Problema con Nueva entidad

### ISSUE THREAD

**Issue by donajivalencia** [cnb-angelus/AngelusIssues#41]
**Describe el problema**
El anotador no me permite ingresar nuevas entidades de "Persona" y sí me deja añadir otras como del tipo "Detención"

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'Documento "Capture Lucio Cabañas" '
2. Haga clic en 'agregar nueva entidad de clase "Persona".'
3. Desplácese hacia abajo 'sólo aparece la opción de Cancelar Nueva Entidad"
4. Ver error

**Comportamiento esperado**
Debe permitirme registrar una nueva entidad con una opción similar a "Nueva Entidad Lista"

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/77068058/103942888-babc1f80-50f6-11eb-85b5-511208c593e4.png)

**Escritorio (complete la siguiente información):**
 - SO: [Windows]
 - Navegador [chrome]
 - Versión del Navegador [87]

**Contexto adicional**
Esto me sucedió desde ayer

**Comment by syats** [comment]
No deberian verse "agregar entidad existente" y  "nueva propiedad" a la vez. Bug.

**Comment by donajivalencia** [comment]
El problema persiste. El anotador no me permite añadir una entidad. 
![image](https://user-images.githubusercontent.com/77068058/104831936-de980780-5852-11eb-9b62-c772bb71d4c4.png)

SO:Windows
Navegador: Chrome
Versión: 87

**Comment by donajivalencia** [comment]
Nuevamente el problema se presenta en otro documento; sin embargo, parece que sólo ocurre con "persona" o con "servidor público", pues sí me dejó añadir la entidad "evento".
![image](https://user-images.githubusercontent.com/77068058/104832130-60d4fb80-5854-11eb-8715-d5803432c83d.png)

**Comment by donajivalencia** [comment]
El problema persiste aún en la nueva versión del anotador. Únicamente con la propiedad "Nombres propios" no es posible guardar una entidad. En el presente documento, me dejó añadir la propiedad "Nombre" pero no la de "Nombres propios"
![image](https://user-images.githubusercontent.com/77068058/106030750-15acbb00-6094-11eb-800a-05f02e17791b.png)

SO:Windows
Navegador: Chrome

**Comment by syats** [comment]
Este bug era porque no se podía agregar entidades sin que tuvieran la propiedad "tieneNombre". Así son los ejemplos que están en los screenshots. 

Esta restricción se ha relajado, @donajivalencia , podrías checar que ahora tenga el comportamiento deseado?

**Comment by syats** [comment]
Si sigue sin funcionar, por favor re-abre el issue. Gracias!
