### ISSUE TITLE
[Visualizador] Mejora: Posibilidad de vaciar canva de manera veloz

### ISSUE THREAD

**Issue by Hector-Bravo** [cnb-angelus/AngelusIssues#45]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.**
Al explorar las distintas relaciones posibles de las entidades se me acabó el canva y hubo que borrar una por una las varias tarjetas colocadas. 

**Describe la solución que te gustaría**
Un botón que al apretarlo elimine todas las tarjetas y relaciones mostradas en el canva. 

**Describe las alternativas que has considerado**
Un canva mucho, mucho, más grande. 

**Contexto adicional**
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí.
![imagen](https://user-images.githubusercontent.com/77067974/104042392-1393c280-51a0-11eb-94a5-32e03ffee953.png)

**Comment by mar-esther23** [comment]
Solución: dale refresh/recargar a la página y eso debe de borrar todo.
