### ISSUE TITLE
[Anotador] no está reconociendo las relaciones de jerarquía entre clases y subclases

### ISSUE THREAD

**Issue by mar-esther23** [cnb-angelus/AngelusIssues#50]
Se comenta también en la minuta:
El anotador no está reconociendo las relaciones de jerarquía entre clases y subclases: no pone en “personas” lo que fue clasificado como “familiares”, “víctimas directas”, etc. Esto complica bastante.

_Originally posted by @donajivalencia in https://github.com/cnb-angelus/AngelusIssues/issues/30#issuecomment-755833891_

Relacionado, no es posible agregar una subclase nueva a una Persona o Evento

**Comment by syats** [comment]
@syats:   en el API, checar que la materialización de subclases esté funcionando.
                en el anotador, agregar un elemento de agregara sublcase.

**Comment by syats** [comment]
@mar-esther23  podrías verificar si ya está resuelto en la nueva versión?
