### ISSUE TITLE
[Anotador] ¿La clase 'evento' podría servir para anotar algún hecho que no esté especificado ya en el sistema y no haya sido contemplado como subclase todavía?

### ISSUE THREAD

**Issue by aaron271** [cnb-angelus/AngelusIssues#54]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.**
Para anotar un evento, como una detención por ejemplo, el sistema ofrece la posibilidad de ingresarlo como la clase 'evento' (con la opción de especificar de qué se trata en el nombre y las observaciones) o de forma específica, por ejemplo como la subclase 'detención'.

**Describe las alternativas que has considerado**
Asumiendo que lo mejor es ingresar al sistema directamente las subclases, ¿la clase 'evento' podría servir en un caso de emergencia para anotar algún hecho que no esté especificado en el sistema como subclase y no haya sido contemplado todavía?

**Comment by mar-esther23** [comment]
Si, pero esto debe de ir en discusión
