### ISSUE TITLE
[Anotador] Mejorar navegacion de clases/subclases

### ISSUE THREAD

**Issue by mar-esther23** [cnb-angelus/AngelusIssues#55]
**Describe el problema**
Si, yo tengo un comentario súper pequeño, casi cosmético (pero que seguro implica mucha chamba de su lado). Tal vez valdría la pena añadir a los elementos de la ontología su clase para que sea más fácil encontrarlos. Así como los que comienzan con Org: Orgcivil, Orgperpetradora, etc. Podríamos tener PersonaVíctima Directa, Persona Familiar o EventoCaptura, EventoTraslado. Pero tal vez no sea muy importante

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a '...'
2. Haga clic en '....'
3. Desplácese hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Una descripción clara y concisa de lo que esperaba que sucediera.

**Capturas de pantalla**
Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.

**Escritorio (complete la siguiente información):**
 - SO: [p. Ej. Windows, Mac]
 - Navegador [p. Ej. cromo, safari]
 - Versión del Navegador [p. Ej. 22]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by mar-esther23** [comment]
@syats esto ya fue parcialmente resuelto, ya que quite las subclases de organización, lo cual debe de simplificar la navegación. Sin embargo, aun queda la pregunta de si agregar un prefijo ya sea a nivel ontología o anotador/visualizador para mejorar la navegación. ¿Opinión?

**Comment by syats** [comment]
@syats  Poner entre paréntesis la superclase
