### ISSUE TITLE
[Anotador] El navegador advierte que el anotador no es un sitio seguro.

### ISSUE THREAD

**Issue by efrainnavarro** [cnb-angelus/AngelusIssues#56]
**Describe el problema**
El navegador reporta al anotador como sitio no seguro.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'https://anotador.pruebascnb.org/ann.html#/Lista'
2. Ver error

**Comportamiento esperado**
Que el navegador reconozca el sitio como seguro.

**Capturas de pantalla**
![6](https://user-images.githubusercontent.com/77067954/104766955-00996900-5731-11eb-8f4a-e35d2680924b.jpg)

**Escritorio (complete la siguiente información):**
 - SO: [Windows]
 - Navegador [Chrome]
 - Versión del Navegador [Versión 87.0.4280.141]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by donajivalencia** [comment]
Tengo exactamente el mismo problema
SO: Windows
Navegador: Chrome
Versión: 87.0.4280.141
![image](https://user-images.githubusercontent.com/77068058/104768380-26c00880-5733-11eb-9b90-bedab99d4212.png)

**Comment by Donnovan17** [comment]
Me ocurrió lo mismo, y fue a partir del día de hoy.
SO: MAC
Navegador: Chrome
Versión: 87.0.4280.141

**Comment by syats** [comment]
@efrainnavarro  @Donnovan17 @donajivalencia  podrían checar si esto sigue pasando?
Gracias!

**Comment by efrainnavarro** [comment]
> @efrainnavarro @Donnovan17 @donajivalencia podrían checar si esto sigue pasando?
> Gracias!

En mi caso ya no ocurre.
