### ISSUE TITLE
[Anotador] Problema con ingresar nueva entidad Perpetrador Apellido Paterno

### ISSUE THREAD

**Issue by Donnovan17** [cnb-angelus/AngelusIssues#57]
**Describe el problema**
Quiero ingresar entidad perpetrador del que únicamente se conoce el apellido Martínez, quiero ingresar sólo apellido paterno Martínez para identificarlo pero no me da la opción de aceptar nueva entidad, sólo permite cancelar nueva entidad.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'documento'
2. Haga clic en 'en nueva entidad, escoja perpetrador, después apellido paterno e ingrese el apellido'
4. Ver error

**Comportamiento esperado**
Debería permitirme ingresar esa entidad apareciendo el botón aceptar nueva entidad.

**Capturas de pantalla**

<img width="2046" alt="Captura de Pantalla 2021-01-19 a la(s) 14 06 46" src="https://user-images.githubusercontent.com/77172310/105087136-a7e30c80-5a5f-11eb-8c06-a00eea8fee21.png">

**Escritorio (complete la siguiente información):**
 - SO: [MAC]
 - Navegador [Google Chromei]
 - Versión del Navegador [87.0.4280.141

**Comment by syats** [comment]
Sí, en este momento esa funcionalidad es esperada. Pero, es cierto, tiene limitaciones.

Esbozo de solución:

Solo aplicará para Persona:
1: Hacer lista de propiedades que van a formar el nombre (e.g. apellidos, alias, etc)
2: Quitar tieneNombre del frontEnd
3: Autocomputar el valor de tieneNombre con los campos de la lista 1. Solo dejar que se guarde si es distinto de vacio.

**Comment by syats** [comment]
@Donnovan17  podrías ver si ya funciona? gracias.
