### ISSUE TITLE
[Credenciales] Mejora: Certificados con caducidad para acceso

### ISSUE THREAD

**Issue by JavierYankelevich** [cnb-angelus/AngelusIssues#59]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.**
No uno actual.

**Describe la solución que te gustaría**
Que los usuarios de Angelus tuvieran un certificado instalado en su computadora/navegador como requisito para loguearse. Eso previene que cualquiera acceda sólo con usuario y contraseña (se requiere, además, el equipo del usuario).

**Comment by JavierYankelevich** [comment]
Las credenciales podrían tener una caducidad (anual, por ejemplo), con lo cual se purgan los usuarios desvinculados del proyecto (aunque se genera un costo adicional en gestión, pues hay que crear y distribuir certificados nuevos a todo el mundo)

**Comment by syats** [comment]
Symetric TLS. Traefik lo soporta, pero necesitamos más expertise en configuración. Nunca hemos trabajado con TLS simétrico.
