### ISSUE TITLE
[General] Mejora: lista de requerimientos mínimos para todos los sistemas

### ISSUE THREAD

**Issue by mar-esther23** [cnb-angelus/AngelusIssues#63]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.**
Una descripción clara y concisa de cuál es el problema. Ex. Siempre me frustra cuando [...]

**Describe la solución que te gustaría**
Una descripción clara y concisa de lo que quieres que suceda.

**Describe las alternativas que has considerado**
Una descripción clara y concisa de cualquier solución o característica alternativa que haya considerado.

**Contexto adicional**
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí.

**Comment by mar-esther23** [comment]
> **Describe el problema**
> No corre
> 
> **Cómo reproducir**
> Pasos para reproducir el comportamiento:
> 
>     1. Vaya a '...'
> 
>     2. Haga clic en '....'
> 
>     3. Desplácese hacia abajo hasta '....'
> 
>     4. Ver error
> 
> 
> **Comportamiento esperado**
> Una descripción clara y concisa de lo que esperaba que sucediera.
> 
> **Capturas de pantalla**
> Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.
> 
> **Escritorio (complete la siguiente información):**
> 
>     * SO: Windows
> 
>     * Navegador IE
> 
>     * 1.0
> 
> 
> **Contexto adicional**
> Agregue aquí cualquier otro contexto sobre el problema.

**Comment by syats** [comment]
Chrome o Firefox estarían en los browsers soportados. IE (espero que quieran decir edge, y no explorer) está dificil de probar :(

**Comment by syats** [comment]
Navegadores Soportados:  Chrome y Firefox
                      No Soportados: Opera, Safari (aunque a veces funciona)

Memoria RAM: 500MB disponibles
