### ISSUE TITLE
[Ontologia] Mejora: agregar campo de código a los lugares

### ISSUE THREAD

**Issue by mar-esther23** [cnb-angelus/AngelusIssues#68]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.**
Si, hay fichas donde se dice el código militar del lugar

**Describe la solución que te gustaría**
Una descripción clara y concisa de lo que quieres que suceda.

**Describe las alternativas que has considerado**
Una descripción clara y concisa de cualquier solución o característica alternativa que haya considerado.

**Contexto adicional**
Agregue cualquier otro contexto o capturas de pantalla sobre la solicitud de función aquí.

**Comment by syats** [comment]
Se necesita algo para asegurarse que un Lugar no tenga un estado y un municipio incompatibles.
Esta lógica podría ir en el anotador, o en el API.

**Comment by mar-esther23** [comment]
Agregado a OntologíaV3
