### ISSUE TITLE
[Visualizador] Problemas con eliminación de tarjetas y relaciones

### ISSUE THREAD

**Issue by JavierYankelevich** [cnb-angelus/AngelusIssues#69]
**Describe el problema**
1) No se pueden eliminar relaciones. 
2) Una vez eliminada una tarjeta, no deja volver a colocarla. 

**Cómo reproducir**

Es posible que dos tarjetas estén relacionadas de más de una manera. Ejemplo:

![imagen](https://user-images.githubusercontent.com/77034019/108760338-245f8400-7513-11eb-8869-6e15d338c044.png)

Es imposible eliminar relaciones de la visualización. Podría eliminarse alguna de las tarjetas, y sólo poner la relación de interés. Sin embargo, una vez eliminada una tarjeta, ya no la muestra de nuevo: 

![imagen](https://user-images.githubusercontent.com/77034019/108760492-57a21300-7513-11eb-8efc-7e84f1429fa3.png)

**Comportamiento esperado**
1) Posibilidad de eliminar relaciones de la visualización
2) Que la tarjeta saliera si el usuario la vuelve a colocar después de eliminarla. 

**Capturas de pantalla**
Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.

**Escritorio (complete la siguiente información):**
 - SO: [p. Ej. Windows, Mac]
 - Navegador [p. Ej. cromo, safari]
 - Versión del Navegador [p. Ej. 22]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by syats** [comment]
Este parece estar arerglado. @JavierYankelevich  lo voy a cerrar, si sigue pasandolo, ábrelo de nuevo.
