### ISSUE TITLE
[Anotador] Navegador indica que el anotador es un sitio no seguro

### ISSUE THREAD

**Issue by efrainnavarro** [cnb-angelus/AngelusIssues#70]
**Describe el problema**
El navegador indica que el anotador es un sitio no seguro.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'Anotador'
4. Ver error

**Comportamiento esperado**
Acceder normalmente al navegador

**Capturas de pantalla**
![7](https://user-images.githubusercontent.com/77067954/109440293-67c85f80-79f7-11eb-96c9-efc8c934d0bf.jpg)

**Escritorio (complete la siguiente información):**
 - SO: Windows 10
 - Navegador [Chrome]
 - Versión del Navegador 88.0.4324.190

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by syats** [comment]
Error de configuración de mi lado.  Debe estar resuelto en unos minutos.

Gracias por reportar.
