### ISSUE TITLE
[Anotador] Problema con la visualización del documento

### ISSUE THREAD

**Issue by donajivalencia** [cnb-angelus/AngelusIssues#72]
**Describe el problema**
Recién subí documentos y al momento en que quiero hacer anotaciones, no se ve

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a SEDENA,_Caja_1434-74-01-19_a_74-12-12-247 (o final 248 ó 305)
2. Haga clic en el documento para ver las anotaciones
3. Esperar a que cargue el documento
4. Ver error

**Comportamiento esperado**
Debería verse el documento para lectura y realizar anotaciones

**Capturas de pantalla**
Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.
![imagen](https://user-images.githubusercontent.com/77068058/110719081-d2d11d80-81d1-11eb-8cfe-3e3f577df86b.png)

**Escritorio (complete la siguiente información):**
 - SO: Windows
 - Navegador: Firefox
 - Versión del Navegador: 86.0

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by syats** [comment]
Revisando, ese documento es un JPEG. Ahorita el anotador solo soporta PDFs de una sola página.

https://repo.pruebascnb.org/file.xhtml?persistentId=doi:10.1/ANGELUS/9ETFZF/WD0DUO&version=DRAFT
