### ISSUE TITLE
[Visualizador] Los nodos saltan constantemente

### ISSUE THREAD

**Issue by mar-esther23** [cnb-angelus/AngelusIssues#73]
**Describe el problema**
Los nodos saltan constantemente aún cuando no se esta agregando nada, este comportamiento perdura por varios segundos y llegan a moverse de posición bastante.
Esto se complica por que muchos de los nodos nuevos aparecen en la esq superior derecha, donde se apilan y generan problemas entre ellos.
Intuyo que es problema de los valores de peso o animación del algoritmo de graficación de redes

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Agregue varios nodos a la vez (aprox 10)
2. Mueva un nodo o agregue uno nuevo

**Comportamiento esperado**
Al agregar un nodo la animación debe de ser mínima o inexistente

**Capturas de pantalla**
Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.

**Escritorio (complete la siguiente información):**
 - SO: [p. Ej. Windows, Mac]
 - Navegador [p. Ej. cromo, safari]
 - Versión del Navegador [p. Ej. 22]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by syats** [comment]
Usar Force-feedback solo cuando aparece el nodo en el canvas, una vez que se acomode, que se haga Pin

**Comment by syats** [comment]
parece funcionar :)
