### ISSUE TITLE
[Visualizador] No se puede acceder a documento original

### ISSUE THREAD

**Issue by mar-esther23** [cnb-angelus/AngelusIssues#87]
**Describe el problema**
Al ver la ficha de wiki debería de ser posible ir al documento donde se genero la anotación, sin embargo esto no es factible

**Cómo reproducir**

**Comportamiento esperado**
Al dar click en la sección de documento debería de mostrar link y llevar al documento

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/3729522/114726252-d42ac400-9d02-11eb-88a5-b256cdc2e6ed.png)

**Escritorio (complete la siguiente información):**

**Contexto adicional**
Posible que el error este en API o Dataverse

**Comment by syats** [comment]
@tzolkingarduno  hay que hacerun url rewrite en el reverse proxy

**Comment by syats** [comment]
Listo, con un hack para el de prueba.
