### ISSUE TITLE
[Anotador] Problema con entidades que no pertenecen a un documento

### ISSUE THREAD

**Issue by donajivalencia** [cnb-angelus/AngelusIssues#88]
**Describe el problema**
En el anotador de pruebas hay un documento en el que aparecen entidades que no están mencionadas en el documento mismo.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'FP-0359 (PRUEBA)' 
2. Ver que las entidades no aparecen en el documento

**Comportamiento esperado**
En este documento sólo debería aparecer la entidad Persona que corresponde a Víctor Acosta Ramos, el resto no forman parte de la información documental. 

**Capturas de pantalla**
![Captura de Pantalla 2021-07-16 a la(s) 8 48 12](https://user-images.githubusercontent.com/77068058/125965908-0450c4d9-1508-4aac-bca9-4723f30ed8cc.png)

**Escritorio (complete la siguiente información):**
 - SO: MacOs Big Sur 11.4
 - Navegador: Safari
 - Versión del Navegador: 14.1.1

**Contexto adicional**
A pesar de que no tengo credenciales propias del anotador de prueba, alguien me prestó las suyas para realizar actividades complementarias al manual y pude notar el error.

**Comment by efrainnavarro** [comment]
Las entidades había sido anotadas como parte de la capacitación, aunque no estuvieran en el documento.

**Comment by efrainnavarro** [comment]
Las entidades había sido anotadas como parte de la capacitación, aunque no estuvieran en el documento.
