### ISSUE TITLE
[Anotador] Problema con el anotador, se borraron las anotaciones después de haberlas introducido y cerrar la sesión

### ISSUE THREAD

**Issue by donnetesquivel** [cnb-angelus/AngelusIssues#91]
**Describe el problema**
Se realizaron unas anotaciones y al cerrar la sesión y abrirla al dia siguiente ya no estaban.

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a '...'
2. Haga clic en '....'
3. Desplácese hacia abajo hasta '....'
4. Ver error

**Comportamiento esperado**
Una descripción clara y concisa de lo que esperaba que sucediera.

**Capturas de pantalla**
Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.
Opriman F12, debe aparecer una barra abajo, revisen estar en el tab de Console y capturen la pantalla con ImpPt.

**Escritorio (complete la siguiente información):**
 - SO: Windows
 - Navegador Chrome
 - Versión del Navegador 92.0.4515.131

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by syats** [comment]
Gracias por reportar, algunas preguntas @donnetesquivel :

1. En qué sistema fue esto: prueba o productivo?
2. En qué documento fue?
3. Cuándo fue esto?

Estoy investigando, cualquier informacion adicional que tengas estaría super.

**Comment by syats** [comment]
Can not reproduce.
