### ISSUE TITLE
[Repositorio] No se pueden agregar páginas a páginas separadas.

### ISSUE THREAD

**Issue by ElizabethNava** [cnb-angelus/AngelusIssues#92]
**Describe el problema**
Al querer subir una pagina en el dataverse de paginas separadas no aparece la opción 

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'repositorio'
2. Haga clic en 'dataverse'
3. Desplácese hacia abajo hasta 'paginas separadas'
4. Ver error: no hay opción para agregar nuevo documento 

**Comportamiento esperado**
Botón Add data  para cargar el documento. 

**Capturas de pantalla**
Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.
Opriman F12, debe aparecer una barra abajo, revisen estar en el tab de Console y capturen la pantalla con ImpPt.
![image](https://user-images.githubusercontent.com/87724450/129811654-8cbf7d97-6366-4c55-ada0-3480d22f44b8.png)
![image](https://user-images.githubusercontent.com/87724450/129812282-d53c6420-4631-4af5-a5d2-4edda8f4fff4.png)

**Escritorio (complete la siguiente información):**
 - SO: [Windows]
 - Navegador [Chrome]
 - Versión del Navegador [Versión 92.0.4515.159 (Build oficial) (64 bits)]

**Contexto adicional**
Agregue aquí cualquier otro contexto sobre el problema.

**Comment by viviana-beltran** [comment]
También tengo el mismo problema, al querer subir una pagina en el dataverse de páginas separadas no aparece la opción de agregar datos. 
![Captura](https://user-images.githubusercontent.com/87626157/129814713-3898317b-5142-4d5e-986f-8cf420be48ca.jpg)

**Comment by syats** [comment]
Es un problema de permisos en el dataverse.
Pero todo esto va a cambiar cuando esté lista la separación por páginas.
