### ISSUE TITLE
[Anotador] Problema con Documentación en Anotador

### ISSUE THREAD

**Issue by Cinclan87** [cnb-angelus/AngelusIssues#93]
**Describe el problema**
Los documentos guardados desde el repositorio no aparecen en la plataforma Test del anotador
Una descripción clara y concisa del problema

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a   https://test-anotador.pruebascnb.org/ann.html#/Lista
2. Haga clic en '....'
3. Desplácese hacia abajo hasta el final de la lista o use Ctrl+F para buscar el nombre del nuevo documento
4. El documento no aparece 

**Comportamiento esperado**
El documento subido desde el repositorio https://repo.pruebascnb.org/ debería añadirse a la lista del anotador, pero no aparece. 

**Capturas de pantalla**

Si corresponde, agregue capturas de pantalla para ayudar a explicar su problema.
Opriman F12, debe aparecer una barra abajo, revisen estar en el tab de Console y capturen la pantalla con ImpPt.

**Escritorio (complete la siguiente información):**
 - SO: Windows 10 Education
 - Navegador: Google Chrome
 - Versión del Navegador: Versión 92.0.4515.159 (Build oficial) (64 bits)
 
 - **Contexto adicional**
![1](https://user-images.githubusercontent.com/88107236/131039743-62ee0172-4997-4d26-9329-c8e0f814e37d.PNG)

Agregue aquí cualquier otro contexto sobre el problema.

**Comment by syats** [comment]
Si quieren ver un documento en  https://test-anotador.pruebascnb.org/ann.html#/Lista
Tienen que subirlo en  https://test-repo.pruebascnb.org/

Pueden verificar si esto funciona?

**Comment by Cinclan87** [comment]
Ya funciona. ¡Gracias!
