### ISSUE TITLE
[Anotador] Problema con el recuadro de las fechas en el anotador

### ISSUE THREAD

**Issue by donajivalencia** [cnb-angelus/AngelusIssues#94]
**Describe el problema**
El calendario para añadir una fecha en el anotador se ve incompleto

**Cómo reproducir**
Pasos para reproducir el comportamiento:
1. Vaya a 'AGN_DFS_C.5_Copia maestra_[Roque Reyes García]_f.202 - '
2. Intente añadir un evento y haga clic en cualquier campo para introducir una fecha, puede ser 'inicio cota inferior'
3. Ver error

**Comportamiento esperado**
El documento no debería romper la visualización del calendario
**Capturas de pantalla**
![Captura de Pantalla 2021-09-06 a la(s) 13 25 37](https://user-images.githubusercontent.com/77068058/132252390-68d556dc-b768-4c4b-8497-8e9906fc6721.png)

**Escritorio (complete la siguiente información):**
 - SO: [macOS Big Sur 11.5.2]
 - Navegador [Safari]
 - Versión del Navegador [14.1.2]

**Comment by syats** [comment]
Usemos Chrome, que es lo que podemos usar para desarrollo.
