### ISSUE TITLE
[Anotador] Mejora: Filtro de búsqueda de documentos

### ISSUE THREAD

**Issue by donajivalencia** [cnb-angelus/AngelusIssues#95]
**¿Su solicitud de función está relacionada con un problema? Por favor describa.**
La lista de los documentos en el anotador ya es muy larga y alenta la selección del documento a anotar.
**Describe la solución que te gustaría**
Existencia de un filtro de búsqueda de documento por nombre, fecha o anotador, etc.

**Describe las alternativas que has considerado**
Ninguna.

**Contexto adicional**
![Captura de Pantalla 2021-09-23 a la(s) 10 33 24](https://user-images.githubusercontent.com/77068058/134537987-915a4bd8-5b72-4648-bd67-8213d1d2ecaf.png)

**Comment by syats** [comment]
Se está trabajando en esta funcionalidad.
Ya está búsqueda en el front
Falta paginacion desde el backend (ya está en el front)

**Comment by mar-esther23** [comment]
Duplicado con #104

**Comment by mar-esther23** [comment]
Incluido parcialmente en V2 del anotador. Faltarían filtros de fecha/anotador
